# Generated by Django 4.1.2 on 2022-11-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaCoche', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img_url',
            field=models.CharField(default='hello', max_length=200),
            preserve_default=False,
        ),
    ]
