# Generated by Django 4.1.2 on 2022-11-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaCoche', '0003_alter_car_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='img_url',
            field=models.CharField(max_length=512),
        ),
    ]
