# Generated by Django 4.1.2 on 2022-11-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaCoche', '0004_alter_car_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
