# Generated by Django 4.1.2 on 2022-11-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaCoche', '0006_categoria_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carID', models.IntegerField(max_length=5)),
                ('categoria', models.IntegerField(max_length=5)),
            ],
        ),
    ]
