# Generated by Django 4.1.2 on 2022-11-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaCoche', '0007_transmision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmision',
            name='carID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transmision',
            name='categoria',
            field=models.IntegerField(),
        ),
    ]
