# Generated by Django 4.1.2 on 2022-11-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaCoche', '0008_alter_transmision_carid_alter_transmision_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transmision',
        ),
    ]
