# Generated by Django 4.1.2 on 2022-11-29 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaCoche', '0009_delete_transmision'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='appEmpresaCoche.marca'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appEmpresaCoche.car')),
                ('transmissionIDs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appEmpresaCoche.categoria')),
            ],
        ),
    ]
