# Generated by Django 4.1.2 on 2022-12-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaCoche', '0010_car_marca_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='img_url',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
