# Generated by Django 4.1.2 on 2022-12-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaCoche', '0011_marca_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='descripcion',
            field=models.CharField(default='UwU', max_length=1024),
            preserve_default=False,
        ),
    ]
