# Generated by Django 4.1.2 on 2022-12-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaCoche', '0013_categoria_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(default='popopopo', max_length=1024),
            preserve_default=False,
        ),
    ]
